- name: Create Bridge Domains
  cisco.aci.aci_bd:
    tenant: "{{ aci_tenant }}"
    bd: "{{ item }}"
    vrf: "{{ aci_vrf }}"
    state: present
    validate_certs: no
  loop: "{{ bridge_domains_list }}"

- name: Add Subnets to Bridge Domains
  cisco.aci.aci_bd_subnet:
    tenant: "{{ aci_tenant }}"
    bd: "{{ item.bd }}"
    gateway: "{{ item.gateway }}"
    mask: "{{ item.mask }}"
    scope: "{{ item.scope }}"
    state: present
    validate_certs: no
  loop: "{{ subnets_list }}"

